const FUNDING_SOURCES=[{id:1,name:"USDA Rural Business Development Grant",provider:"USDA Rural Development",type:"Grant",amount_min:10000,amount_max:500000,deadline:"Rolling",url:"https://www.rd.usda.gov/programs-services/business-programs/rural-business-development-grants",eligibility:["rural_location","for_profit","nonprofit"],description:"Supports rural businesses with technical assistance and training"},{id:2,name:"Amber Grant for Women",provider:"WomensNet",type:"Grant",amount_min:10000,amount_max:10000,deadline:"Monthly",url:"https://www.womensnet.org/amber-grant/",eligibility:["woman_owned"],description:"Monthly $10,000 grant for women entrepreneurs"},{id:3,name:"FedEx Small Business Grant",provider:"FedEx",type:"Grant",amount_min:5000,amount_max:50000,deadline:"Annual (Spring)",url:"https://www.fedex.com/en-us/small-business/grant-contest.html",eligibility:["small_business"],description:"Annual contest for small businesses"},{id:4,name:"Kiva Microloan",provider:"Kiva",type:"Loan",amount_min:1000,amount_max:15000,deadline:"Rolling",url:"https://www.kiva.org/borrow",eligibility:["underserved","any"],description:"0% interest crowdfunded loans"},{id:5,name:"SBA Microloan Program",provider:"US Small Business Administration",type:"Loan",amount_min:500,amount_max:50000,deadline:"Rolling",url:"https://www.sba.gov/funding-programs/loans/microloans",eligibility:["small_business"],description:"Small loans for working capital and equipment"},{id:6,name:"Cartier Women's Initiative",provider:"Cartier",type:"Grant",amount_min:100000,amount_max:100000,deadline:"Annual (Spring)",url:"https://www.cartierwomensinitiative.com/",eligibility:["woman_owned","social_impact"],description:"$100K grants for women entrepreneurs with social impact"},{id:7,name:"Veteran Business Fund",provider:"StreetShares Foundation",type:"Grant",amount_min:5000,amount_max:5000,deadline:"Monthly",url:"https://streetsharesfoundation.org/veteran-business-awards/",eligibility:["veteran"],description:"Monthly $5K grants for veteran-owned businesses"},{id:8,name:"NASE Growth Grant",provider:"National Association for the Self-Employed",type:"Grant",amount_min:4000,amount_max:4000,deadline:"Quarterly",url:"https://www.nase.org/about-us/benefits/growth-grants",eligibility:["self_employed","small_business"],description:"Quarterly grants for business growth"},{id:9,name:"Appalachian Regional Commission Grants",provider:"Appalachian Regional Commission",type:"Grant",amount_min:10000,amount_max:250000,deadline:"Rolling",url:"https://www.arc.gov/funding-opportunities/",eligibility:["appalachian_region","rural_location"],description:"Economic development grants for Appalachian communities"},{id:10,name:"Visa Everywhere Initiative",provider:"Visa",type:"Grant",amount_min:50000,amount_max:50000,deadline:"Annual (Summer)",url:"https://usa.visa.com/run-your-business/visa-everywhere-initiative.html",eligibility:["fintech","startup"],description:"$50K for fintech startups"}];
function matchUser(formData){const matches=[];const isWoman=formData.getAll('identity').includes('woman');const isVeteran=formData.getAll('identity').includes('veteran');const isMinority=formData.getAll('identity').includes('minority');const amount=formData.get('amount');const state=(formData.get('state')||'').toUpperCase();const amountMap={'micro':[0,5000],'small':[5000,25000],'medium':[25000,100000],'large':[100000,1000000]};const[userMin,userMax]=amountMap[amount]||[0,1000000];const appalachianStates=['TN','KY','WV','VA','NC','SC','GA','AL','MS','OH','PA','NY','MD'];FUNDING_SOURCES.forEach(source=>{let score=50;const reasons=[];if(source.amount_min<=userMax&&source.amount_max>=userMin){score+=20;reasons.push(`Amount range matches ($${source.amount_min.toLocaleString()} - $${source.amount_max.toLocaleString()})`);}
if(isWoman&&source.eligibility.includes('woman_owned')){score+=25;reasons.push("Women-owned business program");}
if(isVeteran&&source.eligibility.includes('veteran')){score+=25;reasons.push("Veteran-owned business program");}
if(isMinority&&source.eligibility.includes('minority')){score+=20;reasons.push("Minority-owned business program");}
if(appalachianStates.includes(state)){if(source.eligibility.includes('appalachian_region')){score+=20;reasons.push("Appalachian region eligibility");}
if(source.eligibility.includes('rural_location')){score+=15;reasons.push("Rural location qualifies");}}
if(source.eligibility.includes('any')||source.eligibility.includes('small_business')){score+=10;reasons.push("Open to all small businesses");}
if(score>=60)matches.push({source:source,score:Math.min(score,100),reasons:reasons});});matches.sort((a,b)=>b.score-a.score);return matches.slice(0,10);}
let p=1;function go(page){document.querySelector(`[data-p="${p}"]`).classList.remove('visible');p=page;document.querySelector(`[data-p="${page}"]`).classList.add('visible');updateProgress();updateWall();window.scrollTo({top:0,behavior:'smooth'});}
function updateProgress(){const pct=((p-1)/4)*100;document.getElementById('marker').style.width=`${pct}%`;document.querySelectorAll('.step').forEach((s,i)=>{s.classList.toggle('current',i+1===p);});}
function updateWall(){document.querySelectorAll('.gallery-wall').forEach(w=>w.classList.remove('active'));document.getElementById(`wall${p}`).classList.add('active');}
function pick(btn,field,val){btn.parentElement.querySelectorAll('.selection').forEach(b=>b.classList.remove('chosen'));btn.classList.add('chosen');document.querySelector(`input[name="${field}"]`).value=val;}
document.querySelectorAll('.check input').forEach(cb=>{cb.addEventListener('change',function(){this.closest('.check').classList.toggle('marked',this.checked);});});
document.getElementById('form').addEventListener('submit',e=>{e.preventDefault();const formData=new FormData(e.target);document.getElementById('curtain').classList.add('open');setTimeout(()=>{const matches=matchUser(formData);const userName=formData.get('name')||'You';const totalFunding=matches.reduce((sum,m)=>sum+m.source.amount_max,0);const highMatch=matches.filter(m=>m.score>=80).length;let findingsHtml='';matches.forEach((match,idx)=>{const s=match.source;const reasonsHtml=match.reasons.map(r=>`<div class="reason">${r}</div>`).join('');findingsHtml+=`<div class="finding"><div class="finding-head"><div><div class="finding-index">#${idx+1}</div><div class="finding-name">${s.name}</div><div class="finding-org">${s.provider}</div></div><div class="match-score">${match.score}</div></div><div class="finding-info"><div class="info-item"><strong>Amount</strong>$${s.amount_min.toLocaleString()} – $${s.amount_max.toLocaleString()}</div><div class="info-item"><strong>Type</strong>${s.type}</div><div class="info-item"><strong>Deadline</strong>${s.deadline}</div></div><div class="finding-desc">${s.description}</div><div class="rationale"><strong>Why This Matches</strong>${reasonsHtml}</div><a href="${s.url}" target="_blank" class="proceed">View Application</a></div>`;});document.getElementById('report').innerHTML=`<div class="report-header"><h1>Your Report</h1><p class="subhead">Curated for ${userName}</p></div><div class="metrics"><div class="metric"><div class="metric-value">${matches.length}</div><div class="metric-name">Opportunities</div></div><div class="metric"><div class="metric-value">$${totalFunding.toLocaleString()}</div><div class="metric-name">Potential</div></div><div class="metric"><div class="metric-value">${highMatch}</div><div class="metric-name">High-Match</div></div></div>${findingsHtml}`;document.getElementById('curtain').classList.remove('open');document.getElementById('exhibition').style.display='none';document.getElementById('report').classList.add('published');window.scrollTo({top:0,behavior:'smooth'});},2500);});
updateProgress();